# imagem para arquitetura arm, contÃ©m o build da imagem isolada

version: "3.3"
services: 
    painel: 
        image: disciplina/painel_de_salas:1.0 
        volumes: 
            - painelbackend:/backend
            - painelfrontend:/frontend
        ports: 
            - 3333:3333
        user: root
        restart: always
        
volumes:
    painelbackend: 
    painelfrontend:
